// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Race_PRN232_Project.Models;

#nullable disable

namespace Race_PRN232_Project.Migrations
{
    [DbContext(typeof(RacePRN232Context))]
    [Migration("20251107152950_DBver2")]
    partial class DBver2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Race_PRN232_Project.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"), 1L, 1);

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ImageId");

                    b.HasIndex("RaceId");

                    b.ToTable("Image", (string)null);
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("LocationId");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("RaceId");

                    b.HasIndex("LocationId");

                    b.ToTable("Race", (string)null);
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.RaceDistance", b =>
                {
                    b.Property<int>("RaceDistanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceDistanceId"), 1L, 1);

                    b.Property<decimal?>("CutoffTimeHours")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("RaceDistanceId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceDistance", (string)null);
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.RaceParticipant", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("DistanceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("RaceId", "UserId")
                        .HasName("PK__RacePart__D4835A70A3903942");

                    b.HasIndex("DistanceId");

                    b.HasIndex("UserId");

                    b.ToTable("RaceParticipant", (string)null);
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.SupportTeam", b =>
                {
                    b.Property<int>("SupportTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportTeamId"), 1L, 1);

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("LeaderId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SupportTeamId");

                    b.HasIndex("LeaderId");

                    b.HasIndex("RaceId");

                    b.ToTable("SupportTeam", (string)null);
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.SupportTeamMember", b =>
                {
                    b.Property<int>("SupportTeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupportTeamMemberId"), 1L, 1);

                    b.Property<bool?>("IsLeader")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<DateTime?>("JoinDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RoleInTeam")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SupportTeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SupportTeamMemberId");

                    b.HasIndex("SupportTeamId");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTeamMember", (string)null);
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<int?>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(201)
                        .HasColumnType("nvarchar(201)")
                        .HasComputedColumnSql("(([FirstName]+' ')+[LastName])", true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105344A7A851D")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.Image", b =>
                {
                    b.HasOne("Race_PRN232_Project.Models.Race", "Race")
                        .WithMany("Images")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK__Image__RaceId__38996AB5");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.Race", b =>
                {
                    b.HasOne("Race_PRN232_Project.Models.Location", "Location")
                        .WithMany("Races")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK__Race__LocationId__31EC6D26");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.RaceDistance", b =>
                {
                    b.HasOne("Race_PRN232_Project.Models.Race", "Race")
                        .WithMany("RaceDistances")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK__RaceDista__RaceI__34C8D9D1");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.RaceParticipant", b =>
                {
                    b.HasOne("Race_PRN232_Project.Models.RaceDistance", "Distance")
                        .WithMany("RaceParticipants")
                        .HasForeignKey("DistanceId")
                        .HasConstraintName("FK__RaceParti__Dista__47DBAE45");

                    b.HasOne("Race_PRN232_Project.Models.Race", "Race")
                        .WithMany("RaceParticipants")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK__RaceParti__RaceI__45F365D3");

                    b.HasOne("Race_PRN232_Project.Models.User", "User")
                        .WithMany("RaceParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__RaceParti__UserI__46E78A0C");

                    b.Navigation("Distance");

                    b.Navigation("Race");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.SupportTeam", b =>
                {
                    b.HasOne("Race_PRN232_Project.Models.User", "Leader")
                        .WithMany("SupportTeams")
                        .HasForeignKey("LeaderId")
                        .HasConstraintName("FK__SupportTe__Leade__3C69FB99");

                    b.HasOne("Race_PRN232_Project.Models.Race", "Race")
                        .WithMany("SupportTeams")
                        .HasForeignKey("RaceId")
                        .IsRequired()
                        .HasConstraintName("FK__SupportTe__RaceI__3B75D760");

                    b.Navigation("Leader");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.SupportTeamMember", b =>
                {
                    b.HasOne("Race_PRN232_Project.Models.SupportTeam", "SupportTeam")
                        .WithMany("SupportTeamMembers")
                        .HasForeignKey("SupportTeamId")
                        .IsRequired()
                        .HasConstraintName("FK__SupportTe__Suppo__412EB0B6");

                    b.HasOne("Race_PRN232_Project.Models.User", "User")
                        .WithMany("SupportTeamMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__SupportTe__UserI__4222D4EF");

                    b.Navigation("SupportTeam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.User", b =>
                {
                    b.HasOne("Race_PRN232_Project.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__User__RoleId__2D27B809");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.Location", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.Race", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RaceDistances");

                    b.Navigation("RaceParticipants");

                    b.Navigation("SupportTeams");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.RaceDistance", b =>
                {
                    b.Navigation("RaceParticipants");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.SupportTeam", b =>
                {
                    b.Navigation("SupportTeamMembers");
                });

            modelBuilder.Entity("Race_PRN232_Project.Models.User", b =>
                {
                    b.Navigation("RaceParticipants");

                    b.Navigation("SupportTeamMembers");

                    b.Navigation("SupportTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
